# Этап сборки
FROM node:18-alpine AS build

WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY ./frontend/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Собираем приложение
RUN npm run build

# Этап production
FROM nginx:stable-alpine

# Копируем собранные файлы
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Удаляем дефолтную конфигурацию nginx
RUN rm -rf /etc/nginx/conf.d/default.conf.default

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]